model_list:
  - model_name: lm_studio/llama3.2-latest
    litellm_params:
      model: lm_studio/llama3.2-latest
      api_key: api-key
  - model_name: lm_studio/phi4-14b
    litellm_params:
      model: lm_studio/phi4-14b
      api_key: api-key
