model_list:
  - model_name: ollama/deepseek-r1:14b
    litellm_params:
      model: ollama/deepseek-r1:14b
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
